name: Compile Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile Spearhead
        uses: dutchie031/DcsMissionScriptingTools/github-action@feature/github-action
        with:
          source-root: ./src
          output-file: ./output/spearhead.lua

      - name: Upload spearhead.lua artifact
        uses: actions/upload-artifact@v4
        with:
          name: spearhead-lua
          path: ./output/spearhead.lua
