name: Compile Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SpearheadCompile
        run: |
          mkdir -p ./output
          python3 SpearheadCompile.py . ./output/spearhead.lua

      - name: Upload spearhead.lua artifact
        uses: actions/upload-artifact@v4
        with:
          name: spearhead-lua
          path: ./output/spearhead.lua
