#start

name: update newsletters
on:
  push:
    branches:
      - main

jobs:
 build:
  name: push_file   
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: .
  steps:
  - name: Setup credentials to access private repositories
    run: git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf https://github.com/
  - name: Push readme to another repository
    uses: nkoppel/push-files-to-another-repository@v1.1.3
    env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    with:
        source-files: 'DOC.md'
        destination-username: 'dutchie032'
        destination-repository: 'dutchie032.github.io '
        destination-directory: 'Spearhead'
        commit-email: 'timrorije@gmail.com'
        commit-username: 'dutchie032'
        destination-branch: 'main'

  