#start

name: update newsletters
on:
  push:
    branches:
      - main

jobs:
 pushdoc:
  name: push_file   
  runs-on: ubuntu-latest
  env:
    branch: main
    username: dutchie032
    repo: dutchie032.github.io 
    sourcefileA: Reference
    sourcefileB: GetStarted
  defaults:
   run:
    working-directory: .
  steps:
  - uses: actions/checkout@v4
    with:
      path: './spearhead'
  - name: ls
    run: ls
  - name: Setup credentials to access private repositories
    run: git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf https://github.com/
  - name: Git Config
    run: git config --global user.email "automated@action.com"
  - name: Git Config
    run: git config --global user.name "automated action"
  - name: clone
    run: git clone --single-branch --branch $branch https://github.com/$username/$repo 
  - name: ls
    run: ls
  - name: mkdir
    run: mkdir -p ./$repo/Spearhead
  - run: npm i markdown-to-html-cli -g
  - run: markdown-to-html --title 'Spearhead' --dark-mode auto  --keywords "dcs,spearhead,tdcs,mission,campaign,tactical dcs,tactical" --no-dark-mode --markdown-style-theme dark --source ./spearhead/docs/$sourcefileA.md --output ./$repo/Spearhead/$sourcefileA.html
  - run: markdown-to-html --title 'Spearhead' --dark-mode auto  --keywords "dcs,spearhead,tdcs,mission,campaign,tactical dcs,tactical" --no-dark-mode --markdown-style-theme dark --source ./spearhead/docs/$sourcefileB.md --output ./$repo/Spearhead/$sourcefileB.html
  - run: cp -a ./spearhead/docs/img/. ./$repo/Spearhead/img/
  - name: ls
    run: ls
    working-directory: ./dutchie032.github.io
  - name: add
    run: git add --a
    working-directory: ./dutchie032.github.io
  - name: commit
    run: git commit -a -m "Automatic Update of Spearhead README"
    working-directory: ./dutchie032.github.io
  - name: push
    run: git push
    working-directory: ./dutchie032.github.io