#start

name: update newsletters
on:
  push:
    branches:
      - main

jobs:
 build:
  name: push_file   
  runs-on: ubuntu-latest
  defaults:
   run:
    working-directory: .
  steps:
  - name: Setup credentials to access private repositories
    run: git config --global url.https://${{ secrets.API_TOKEN_GITHUB }}@github.com/.insteadOf https://github.com/
  - uses: sator-imaging/Copy-to-Another-Repository@v1
    with:
      # required parameters
      target-filepath: 'DOC.md'      # file path to copy
      output-branch: 'main'   # branch name to create pull request
      output-repo: 'dutchie032/dutchie032.github.io'
      output-directory: "Spearhead"  
      git-token: ${{ secrets.API_TOKEN_GITHUB }}
      git-name: "github-actions[bot]"   # your name can be set by ${{ github.actor }}
      git-email: 'github-actions[bot]@users.noreply.github.com'   # associated user icon is shown in commit page