name: Publish Release

on:
  workflow_dispatch:
    inputs:
      release_candidate:
        description: 'Is this a release candidate?'
        required: true
        default: true
        type: boolean
      change_size:
        type: choice
        description: Version Bump
        options: 
        - patch
        - minor
        - major
        default: patch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run SpearheadCompile
      run: |
        mkdir -p ./output
        python3 SpearheadCompile.py . ./output/spearhead.lua


    - name: Check Change size PC
      id: change_size 
      run: |
        size="${{ inputs.change_size }}"
        if [ "${{ inputs.release_candidate }}" = "true" ]; then
          echo "BUMP=pre$size" >> "$GITHUB_OUTPUT"
        else
          echo "BUMP=$size" >> "$GITHUB_OUTPUT"
        fi


    - name: Calculate Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.change_size.outputs.patch_size }}
          default_prerelease_bump: ${{ steps.change_size.outputs.patch_size }}
          dry_run: true
          custom_release_rules: ""
          append_to_pre_release_tag: "rc"

    # - name: Create GitHub Release
    #   uses: actions/create-release@v1
    #   with:
    #     tag_name: ${{ github.ref_name }}
    #     release_name: Release ${{ github.ref_name }}
    #     draft: true
    #     prerelease: ${{ inputs.release_candidate }}
    #     files: |
    #       ./output/spearhead.lua
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

